### ISSUE TITLE
[Question] command line

### ISSUE THREAD

**Issue by r7ings** [liou666/live-parser#1]
I would like to know where the command line output related code is located. I would like to write some code based on the live room broadcast barrage and gift information. I look forward to your reply.

**Comment by liou666** [comment]
@r7ings Maybe you need use the package [@liou666/live-parser-core](https://github.com/liou666/live-parser/tree/main/packages/core), and you can see this core logic here.

**Comment by r7ings** [comment]
i wrote the handler like this but i got nothing output in command line,how should i use this function called run
`import run from '@liou666/live-parser-core'

run(965958390639, (e)=>{
    console.log(e);
})`

**Comment by liou666** [comment]
@r7ings  you need to use it as in the following example👇
```ts
import run from '@liou666/live-parser-core'
run('965958390639', {
  handleChatMessage(data) {
    console.log(data.content)
  },
})
```

**Comment by r7ings** [comment]
it works,thank you very much for helping me!
